//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int AdmissionID { get; set; }
        public string AdmissionNumber { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string Diagnosis { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public string DischargeSummary { get; set; }
    
        public virtual Bed Bed { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
