//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public string Status { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual User User { get; set; }
    }
}
