//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bed()
        {
            this.Admissions = new HashSet<Admission>();
        }
    
        public int BedID { get; set; }
        public string BedNumber { get; set; }
        public Nullable<int> WardID { get; set; }
        public string BedType { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> DailyRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
