//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public string TransactionType { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ReferenceNo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual User User { get; set; }
    }
}
