//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabOrderItem
    {
        public int OrderItemID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string ReferenceRange { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    
        public virtual LabOrder LabOrder { get; set; }
        public virtual LabTest LabTest { get; set; }
    }
}
