//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTest()
        {
            this.LabOrderItems = new HashSet<LabOrderItem>();
        }
    
        public int TestID { get; set; }
        public string TestCode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TestName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string NormalRange { get; set; }
        public string Unit { get; set; }
        public string ProcessingTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabOrderItem> LabOrderItems { get; set; }
        public virtual LabTestCategory LabTestCategory { get; set; }
    }
}
