//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionItem
    {
        public int PrescriptionItemID { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public string Dosage { get; set; }
        public string Frequency { get; set; }
        public string Duration { get; set; }
        public string Notes { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
