//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescription()
        {
            this.PrescriptionItems = new HashSet<PrescriptionItem>();
        }
    
        public int PrescriptionID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<System.DateTime> PrescriptionDate { get; set; }
        public string Instructions { get; set; }
        public string Status { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionItem> PrescriptionItems { get; set; }
    }
}
