//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Activity { get; set; }
        public string Details { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
